import 'package:flutter/material.dart';
import 'package:glowmate_app/main.dart';
import 'package:intl/intl.dart';
import '../../utils/constants.dart';

class MonthlyReport extends StatefulWidget {
  const MonthlyReport({super.key});

  @override
  State<MonthlyReport> createState() => _MonthlyReportState();
}

class _MonthlyReportState extends State<MonthlyReport> {
  bool _isLoading = true;
  // Set to the 1st of the current month
  final DateTime _selectedMonth = DateTime(DateTime.now().year, DateTime.now().month, 1);
  
  // Stats & Saved State
  int _consistencyPercent = 0;
  int? _monthlySkinRating;
  bool _isReportSaved = false;
  String _reportId = "";

  @override
  void initState() {
    super.initState();
    _fetchInitialData();
  }

  // --- 1. FETCH DATA ---
  Future<void> _fetchInitialData() async {
    final user = supabase.auth.currentUser;
    if (user == null) return;
    setState(() => _isLoading = true);

    try {
      final String monthStartStr = DateFormat('yyyy-MM-dd').format(_selectedMonth);
      final DateTime endOfMonth = DateTime(_selectedMonth.year, _selectedMonth.month + 1, 0);
      final String monthEndStr = DateFormat('yyyy-MM-dd').format(endOfMonth);

      // A. Calculate Consistency Percentage
      // We check unique days in routine_logs for the selected month
      final logsResponse = await supabase
          .from('routine_logs')
          .select('log_date')
          .eq('user_id', user.id)
          .gte('log_date', monthStartStr)
          .lte('log_date', monthEndStr);

      final List<dynamic> logs = logsResponse as List<dynamic>;
      final Set<String> uniqueDays = logs.map((e) => e['log_date'].toString()).toSet();
      
      // B. Check if a report already exists for this month
      final reportData = await supabase
          .from('monthly_skin_reports')
          .select()
          .eq('user_id', user.id)
          .eq('report_month', monthStartStr)
          .maybeSingle();

      if (mounted) {
        setState(() {
          _consistencyPercent = ((uniqueDays.length / endOfMonth.day) * 100).round();
          if (reportData != null) {
            _monthlySkinRating = reportData['skin_rating'];
            _reportId = reportData['id'] ?? "";
            _isReportSaved = true;
          }
          _isLoading = false;
        });
      }
    } catch (e) {
      debugPrint("Fetch Error: $e");
      if (mounted) setState(() => _isLoading = false);
    }
  }

  // --- 2. SAVE REPORT (DB Handles ID Generation) ---
  Future<void> _saveMonthlyRating(int rating) async {
    final user = supabase.auth.currentUser;
    if (user == null) return;

    setState(() => _isLoading = true);

    try {
      final monthStr = DateFormat('yyyy-MM-dd').format(_selectedMonth);

      // Upsert data. Note: We do NOT send 'id' because the DB Trigger generates 'msrXXX'
      await supabase.from('monthly_skin_reports').upsert({
        'user_id': user.id,
        'report_month': monthStr,
        'skin_rating': rating,
        'consistency_score': _consistencyPercent,
      }, onConflict: 'user_id, report_month');

      // Re-fetch to get the ID generated by the DB trigger
      final savedData = await supabase
          .from('monthly_skin_reports')
          .select('id')
          .eq('user_id', user.id)
          .eq('report_month', monthStr)
          .single();

      if (mounted) {
        setState(() {
          _monthlySkinRating = rating;
          _reportId = savedData['id'];
          _isReportSaved = true;
          _isLoading = false;
        });
        _showSuccessDialog();
      }
    } catch (e) {
      debugPrint("Save Error: $e");
      if (mounted) {
        setState(() => _isLoading = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error saving report: $e"), backgroundColor: Colors.red),
        );
      }
    }
  }

  void _showSuccessDialog() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: const Text("Success!"),
        content: Text("Monthly Report $_reportId has been generated and saved to your history."),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text("View Report", style: TextStyle(color: PrimaryAccent, fontWeight: FontWeight.bold)),
          )
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios, color: TextColor),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text("Monthly Progress", style: TextStyle(color: TextColor, fontWeight: FontWeight.bold)),
        centerTitle: true,
      ),
      body: _isLoading 
          ? const Center(child: CircularProgressIndicator(color: PrimaryAccent))
          : SingleChildScrollView(
              padding: const EdgeInsets.all(25),
              child: Column(
                children: [
                  // --- Header: Month Display ---
                  Text(
                    DateFormat('MMMM yyyy').format(_selectedMonth).toUpperCase(),
                    style: const TextStyle(letterSpacing: 1.5, fontWeight: FontWeight.bold, color: Colors.grey, fontSize: 13),
                  ),
                  const SizedBox(height: 25),

                  // --- Part 1: Routine Consistency Card ---
                  _buildSectionCard(
                    title: "Routine Consistency",
                    child: Column(
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Icon(Icons.flash_on, color: Colors.amber, size: 30),
                            Text("$_consistencyPercent%", style: const TextStyle(fontSize: 50, fontWeight: FontWeight.bold, color: TextColor)),
                          ],
                        ),
                        const Text("Habit Score", style: TextStyle(color: Colors.grey, fontWeight: FontWeight.w500)),
                        const SizedBox(height: 20),
                        ClipRRect(
                          borderRadius: BorderRadius.circular(10),
                          child: LinearProgressIndicator(
                            value: _consistencyPercent / 100,
                            minHeight: 12,
                            backgroundColor: PrimaryAccent.withOpacity(0.1),
                            color: PrimaryAccent,
                          ),
                        ),
                      ],
                    ),
                  ),

                  const SizedBox(height: 25),

                  // --- Part 2: Skin Status (Saved or Input) ---
                  _isReportSaved ? _buildSavedRating() : _buildRatingPrompt(),
                  
                  const SizedBox(height: 30),
                  
                  if (_isReportSaved) _buildAnalysisMessage(),
                ],
              ),
            ),
    );
  }

  Widget _buildSectionCard({required String title, required Widget child}) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(25),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(25),
        border: Border.all(color: Colors.grey.shade100),
        boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.02), blurRadius: 15, offset: const Offset(0, 5))],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: TextColor)),
          const SizedBox(height: 20),
          child,
        ],
      ),
    );
  }

  Widget _buildRatingPrompt() {
    return _buildSectionCard(
      title: "How was your skin overall this month?",
      child: Column(
        children: [
          const Text("Select a rating to lock in your monthly report.", style: TextStyle(fontSize: 13, color: Colors.grey)),
          const SizedBox(height: 25),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: List.generate(5, (index) {
              int rating = index + 1;
              return GestureDetector(
                onTap: () => _saveMonthlyRating(rating),
                child: Column(
                  children: [
                    Icon(
                      rating <= 2 ? Icons.sentiment_dissatisfied : (rating == 3 ? Icons.sentiment_neutral : Icons.sentiment_very_satisfied),
                      size: 42, 
                      color: Colors.grey.shade300
                    ),
                    const SizedBox(height: 8),
                    Text("$rating", style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.grey)),
                  ],
                ),
              );
            }),
          ),
        ],
      ),
    );
  }

  Widget _buildSavedRating() {
    return _buildSectionCard(
      title: "Monthly Skin Status",
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 15),
        decoration: BoxDecoration(
          color: PrimaryAccent.withOpacity(0.05),
          borderRadius: BorderRadius.circular(15),
          border: Border.all(color: PrimaryAccent.withOpacity(0.1)),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.auto_awesome, color: PrimaryAccent, size: 28),
            const SizedBox(width: 15),
            Text("$_monthlySkinRating / 5", style: const TextStyle(fontSize: 36, fontWeight: FontWeight.bold, color: TextColor)),
            const SizedBox(width: 15),
            const Icon(Icons.auto_awesome, color: PrimaryAccent, size: 28),
          ],
        ),
      ),
    );
  }

  Widget _buildAnalysisMessage() {
    bool isGood = _consistencyPercent >= 75;
    return Container(
      padding: const EdgeInsets.all(20),
      child: Column(
        children: [
          Icon(isGood ? Icons.stars : Icons.info_outline, color: PrimaryAccent, size: 36),
          const SizedBox(height: 15),
          Text(
            isGood 
              ? "Brilliant effort! Your consistency is helping your skin stay healthy. Keep this routine up!"
              : "Every day counts! Try to increase your consistency next month to see even better results.",
            textAlign: TextAlign.center,
            style: const TextStyle(fontSize: 15, color: TextColor, fontStyle: FontStyle.italic, height: 1.6),
          ),
          const SizedBox(height: 10),
          Text("Report Reference: $_reportId", style: const TextStyle(fontSize: 10, color: Colors.grey)),
        ],
      ),
    );
  }
}